### ISSUE TITLE
Question around usage

### ISSUE THREAD

**Issue by argupta23** [go4taj/loopback-import-export-mixin#8]
Hello @go4taj,

Thanks for sharing the plugin.

I followed the steps that you have listed in your Readme.

Followed SETUP / MODEL CONFIG and restarted my application.

Looking into the explorer I don't see the "Export Model data in csv/xls file" option relative to the model (.json file) I updated with your mixin.

Do I need to do anything in the associated JS / TS file to get this mixin to work?  

Thanks

**Comment by go4taj** [comment]
Hi @argupta23 would you please share the model-config.json and your Model.json you want to export?

**Comment by argupta23** [comment]
hello @go4taj,

thanks for the quick response.

**condensed snippets of my model-config.json and devicedef.json are below.**
`{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "../common/models/alert",
      "../common/models/static_file",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins",
      "../node_modules/loopback-ds-timestamp-mixin",
      "../node_modules/loopback3-rt-stats-mixin/dist",
      "../node_modules/loopback-import-export-mixin/src"
    ]
  },
  "User": {
    "dataSource": "mongodb",
    "public": false
  },
  "Email": {
    "dataSource": null,
    "public": false
  },
  "AccessToken": {
    "dataSource": "mongodb",
    "public": true,
    "options": {
      "remoting": {
        "sharedMethods": {
          "*": false
        }
      }
    },
    "relations": {
      "user": {
        "type": "belongsTo",
        "model": "user",
        "foreignKey": "userId"
      }
    },
    "acls": [
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$owner",
        "permission": "ALLOW",
        "property": "deleteById"
      }
    ]
  },
  "ACL": {
    "dataSource": "mongodb",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "mongodb",
    "public": false
  },
  "Role": {
    "dataSource": "mongodb",
    "public": true,
    "acls": [
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$everyone",
        "permission": "DENY"
      },
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "admin",
        "permission": "ALLOW",
        "property": "*"
      }
    ]
  },
  "Devicedef": {
    "dataSource": "mongodb",
    "public": true
 }
}`

 **devicedef.json contains**

`{
  "replaceOnPUT": false,
  "name": "Devicedef",
  "plural": "Devicedefs",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "mixins": {
    "ImportExport": { "export": true },
    "TimeStamp": {
      "required": false,
      "validateUpsert": true
    },
    "Stats": [
      {
        "method": "stats",
        "endpoint": "/stats",
        "description": "Statistical information for Devicedef registers.",
        "type": "model",
        "count": {
          "on": "createdAt",
          "by": "index"
        }
      }
    ]
  },
  "properties": {
    "vendor": {
      "type": "string"
    },
    "make": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "type": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    },
    "Organizations": {
      "type": "hasAndBelongsToMany",
      "model": "Organization",
      "foreignKey": "organizationId"
    },
    "Category": {
      "type": "belongsTo",
      "model": "Category",
      "foreignKey": "categoryId"
    },
    "Messages": {
      "type": "hasMany",
      "model": "Message",
      "foreignKey": "deviceId"
    },
    "Geolocs": {
      "type": "hasMany",
      "model": "Geoloc",
      "foreignKey": "deviceId"
    },
    "Alerts": {
      "type": "hasMany",
      "model": "Alert",
      "foreignKey": "deviceId"
    },
    "Parser": {
      "type": "belongsTo",
      "model": "Parser",
      "foreignKey": "parserId"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "DENY"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": ["find"]
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": ["download"]
    }
  ],
  "methods": {}
}`

**Comment by go4taj** [comment]
Please use the below configuration in your model configuration
`devicedef.json `

`"ImportExport": {
      "export": {}
    }`

Thanks for pointing it out

**Comment by argupta23** [comment]
Hello Taj,

Unfortunately that did not work.

I do have a question for you and the issue might be specific to my environment.

In Explorer with your plugin enabled under "Response content type" do you expect to see a dropdown option for "text/csv"? I am assuming that it would be the case.

If Yes, I don't see that happen in my case, which leads me to believe that we are missing a step somewhere.

Thanks again for your help.

**Comment by otsraisegreen** [comment]
Closing due to inaccurate setup

**Comment by otsraisegreen** [comment]
Closing the issues
